name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.16.1/zola-v0.16.1-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola-v0.16.1-x86_64-unknown-linux-gnu.tar.gz
          sudo mv zola /usr/local/bin/

      - name: Build site with Zola
        run: zola build

      - name: Deploy to DigitalOcean
        uses: digitalocean/app-action@v1
        with:
          api-token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          spec: ./appspec.yml
